openapi: 3.0.3
info:
  title: Vehicle Parking System API
  description: REST API for the Vehicle Parking Management System
  version: 1.0.0
  contact:
    name: Vehicle Parking System
    email: support@parkingsystem.com

servers:
  - url: http://localhost:5000
    description: Development server

paths:
  /api/parking_availability/{lot_id}:
    get:
      summary: Get parking availability for a specific lot
      description: Returns the current availability status of parking spots in a given parking lot
      parameters:
        - name: lot_id
          in: path
          required: true
          description: The unique identifier of the parking lot
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successful response with parking availability data
          content:
            application/json:
              schema:
                type: object
                properties:
                  lot_id:
                    type: integer
                    description: The parking lot identifier
                    example: 1
                  available:
                    type: integer
                    description: Number of available parking spots
                    example: 15
                  total:
                    type: integer
                    description: Total number of parking spots in the lot
                    example: 50
                  occupancy_rate:
                    type: number
                    format: float
                    description: Percentage of occupied spots (rounded to 1 decimal place)
                    example: 70.0
              example:
                lot_id: 1
                available: 15
                total: 50
                occupancy_rate: 70.0
        '404':
          description: Parking lot not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Parking lot not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

components:
  schemas:
    ParkingAvailability:
      type: object
      required:
        - lot_id
        - available
        - total
        - occupancy_rate
      properties:
        lot_id:
          type: integer
          description: Unique identifier for the parking lot
        available:
          type: integer
          description: Number of currently available parking spots
          minimum: 0
        total:
          type: integer
          description: Total capacity of the parking lot
          minimum: 1
        occupancy_rate:
          type: number
          format: float
          description: Percentage of occupied spots
          minimum: 0
          maximum: 100

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message describing what went wrong

tags:
  - name: Parking
    description: Operations related to parking lot management and availability
